import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { identity, snapshot, key, date } from './review-helpers'

test('真实教程播放下载，电脑缩放保留表单内容与路由', async ({ page }) => {
  await page.goto('/')
  await identity(page, '李思敏')
  await expect(page.getByText('business-prd-prototype.zip', { exact: true })).toBeVisible()
  const downloadButton = page.getByRole('button', { name: '下载 Skill 成品包' })
  await expect(downloadButton).toBeEnabled()
  const downloadPromise = page.waitForEvent('download')
  await downloadButton.click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('business-prd-prototype.zip')
  expect(await readFile((await download.path())!)).toEqual(
    await readFile('public/training/20260916/business-prd-prototype.zip')
  )
  await page.getByRole('button', { name: '观看教程', exact: true }).click()
  const video = page.getByRole('dialog', { name: '视频教程 · 如何正确提 0→1 项目需求' })
  const media = video.locator('video')
  await expect(media).toBeAttached()
  await media.evaluate(async (element: HTMLVideoElement) => { element.muted = true; await element.play() })
  await expect.poll(() => media.evaluate((element: HTMLVideoElement) => element.currentTime)).toBeGreaterThan(0)
  await video.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(page.locator('video')).toHaveCount(0)
  await page.screenshot({ path: '../output/playwright/demand-experience-desktop.png', animations: 'disabled' })
  await page.getByRole('button', { name: '提交正式项目需求', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '提交正式项目需求', exact: true })
  await editor.getByLabel('项目名称', { exact: true }).fill('缩小窗口保留的未保存名称')
  for (const width of [930, 600, 1440]) {
    await page.setViewportSize({ width, height: 1000 })
    await expect(editor.getByLabel('项目名称', { exact: true })).toHaveValue('缩小窗口保留的未保存名称')
    await expect(page.getByRole('heading', { name: '请在电脑端使用' })).toHaveCount(0)
    await expect(page).toHaveURL(/#\/my-demands$/)
    await expect.poll(async () => (await editor.boundingBox())!.x).toBeGreaterThanOrEqual(-1)
    await expect.poll(async () => (await editor.boundingBox())!.width).toBeLessThanOrEqual(width)
  }
  await editor.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '放弃修改', exact: true }).click()
  await page.setViewportSize({ width: 930, height: 1000 })
  await expect(page.locator('.el-menu--collapse')).toBeVisible()
  await page.screenshot({ path: '../output/playwright/demand-experience-narrow.png', animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
})

test('教程文件获取失败有提示且可重试', async ({ page }) => {
  await page.goto('/')
  await identity(page, '李思敏')
  const zipPath = '**/training/20260916/business-prd-prototype.zip'
  await page.route(zipPath, route => route.fulfill({ status: 404, body: 'Not found' }))
  await page.getByRole('button', { name: '下载 Skill 成品包' }).click()
  await expect(page.getByText('Skill 成品包暂时无法获取，请稍后重试或联系管理员。')).toBeVisible()
  await page.unroute(zipPath)
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载 Skill 成品包' }).click()
  expect((await download).suggestedFilename()).toBe('business-prd-prototype.zip')
  await expect(page.getByText('Skill 成品包暂时无法获取，请稍后重试或联系管理员。')).toHaveCount(0)
  const videoPath = '**/training/20260916/business-prd-prototype-tutorial.mp4'
  await page.route(videoPath, route => route.fulfill({ status: 404, body: 'Not found' }))
  await page.getByRole('button', { name: '观看教程', exact: true }).click()
  await expect(page.getByText('视频暂时无法加载')).toBeVisible()
  await page.unroute(videoPath)
  await page.getByRole('button', { name: '重新加载', exact: true }).click()
  await expect(page.locator('video')).toBeAttached()
  await page.locator('video').evaluate(async (element: HTMLVideoElement) => { element.muted = true; await element.play() })
  await expect.poll(() => page.locator('video').evaluate((element: HTMLVideoElement) => element.currentTime)).toBeGreaterThan(0)
})

test('需求池选择已完成主项目、按编号搜索、草稿再提交，关联不会误变为正式需求', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  const initial = await snapshot(page)
  const parent = initial.database.projects[0]
  parent.status = 'completed'; parent.simpleStatus = 'completed'; parent.stage = '验收交付'
  parent.actualCompletedAt = '2026-09-10T00:00:00.000Z'
  parent.code = 'XM-2026-8801'
  await page.evaluate(({ k, value }) => localStorage.setItem(k, JSON.stringify(value)), { k: key, value: initial })
  await page.reload()
  await identity(page, '李思敏')
  const before = (await snapshot(page)).database.demands.length
  await page.getByRole('button', { name: '提交优化需求', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '优化需求', exact: true })
  await editor.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect(editor).toContainText('请选择关联原项目')
  expect((await snapshot(page)).database.demands.length).toBe(before)
  await editor.getByRole('combobox', { name: '关联原项目', exact: true }).fill('8801')
  await page.getByRole('option', { name: `${parent.name} · XM-2026-8801`, exact: true }).click()
  await editor.getByLabel('优化标题', { exact: true }).fill('需求池关联项目回归')
  await editor.getByLabel('当前问题', { exact: true }).fill('导出缺少业务部门')
  await editor.getByLabel('期望效果 / 验收标准', { exact: true }).fill('导出包含正确部门')
  await date(editor, '期望完成日期', '2099-10-20')
  await editor.locator('.el-drawer__body').evaluate(el => { el.scrollTop = 0 })
  await page.screenshot({ path: '../output/playwright/demand-experience-optimization.png', animations: 'disabled' })
  await editor.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect(editor).not.toBeVisible()
  const draft = (await snapshot(page)).database.demands.find(d => d.name === '需求池关联项目回归')!
  expect(draft).toMatchObject({ parentProjectId: parent.id, status: 'draft' })
  await page.getByRole('row').filter({ hasText: draft.name }).getByRole('button', { name: '编辑', exact: true }).click()
  await expect(editor.getByRole('combobox', { name: '关联原项目', exact: true })).toHaveCount(0)
  await editor.getByRole('button', { name: '提交优化审批', exact: true }).click()
  await expect(editor).not.toBeVisible()
  expect((await snapshot(page)).database.demands.find(d => d.id === draft.id)).toMatchObject({ parentProjectId: parent.id, status: 'pending' })
  expect((await snapshot(page)).database.projects.find(p => p.id === parent.id)).toEqual(parent)
})

test('无已完成主项目时说明空状态且不产生普通需求', async ({ page }) => {
  await page.goto('/')
  const initial = await snapshot(page)
  initial.database.projects.forEach(p => { p.status = 'active' })
  await page.evaluate(({ k, value }) => localStorage.setItem(k, JSON.stringify(value)), { k: key, value: initial })
  await page.reload()
  await identity(page, '李思敏')
  await page.getByRole('button', { name: '提交优化需求', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '优化需求', exact: true })
  await editor.getByRole('combobox', { name: '关联原项目', exact: true }).click()
  await expect(page.getByText('暂无可关联的已完成主项目', { exact: true })).toBeVisible()
  await editor.getByRole('button', { name: '提交优化审批', exact: true }).click()
  await expect(editor).toContainText('请选择关联原项目')
  expect((await snapshot(page)).database.demands).toEqual(initial.database.demands)
})
