import { expect, test } from '@playwright/test'
import { card, date, identity, reset, snapshot } from './review-helpers'

test('历史交付阻止未保存草稿，校验必填，登记持久化及中文历史', async ({ page }) => {
  await page.goto('/')
  await reset(page)
  await identity(page, '陈立峰')
  const initial = await snapshot(page)
  const project = initial.database.projects.find(p => p.status === 'active' && !p.archived)!
  await card(page, project.name).getByRole('button', { name: '编辑项目', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '编辑项目', exact: true })
  const originalName = await editor.getByLabel('项目名称', { exact: true }).inputValue()
  await editor.getByLabel('项目名称', { exact: true }).fill('未保存名称')
  await editor.getByRole('button', { name: '登记历史已交付', exact: true }).click()
  await expect(editor).toContainText('请先保存或放弃修改')
  await editor.getByLabel('项目名称', { exact: true }).fill(originalName)
  await editor.getByRole('button', { name: '登记历史已交付', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '登记历史已交付', exact: true })
  await dialog.getByRole('button', { name: '确认登记' }).click()
  await expect(dialog).toContainText('实际交付日期不是有效日期')
  await date(dialog, '实际交付日期', '2026-09-15')
  await dialog.getByRole('button', { name: '确认登记' }).click()
  await expect(dialog).toContainText('补录原因须为')
  await dialog.getByLabel('补录原因').fill('旧系统交付记录核对')
  await page.screenshot({ path: 'output/playwright/historical-delivery-dialog.png' })
  await dialog.getByRole('button', { name: '确认登记' }).click()
  await expect(editor).not.toBeVisible()
  const saved = (await snapshot(page)).database.projects.find(p => p.id === project.id)!
  expect(saved.status).toBe('completed')
  expect(saved.actualCompletedAt).toBe('2026-09-15T00:00:00.000Z')
  expect(saved.name).toBe(originalName)
  await page.reload()
  await card(page, saved.name).getByRole('button', { name: '详情', exact: true }).click()
  const detail = page.getByRole('dialog').filter({ hasText: '状态与管理历史' })
  await expect(detail).toContainText('登记历史已交付')
  await expect(detail).toContainText('历史完成 / 无业务验收记录')
  await expect(detail).toContainText('实际完成时间：2026-09-15')
  await page.screenshot({ path: 'output/playwright/historical-delivery-result.png' })
})
