import { expect, test } from '@playwright/test'
import { identity, snapshot, select, date, acceptProposal, row, card } from './review-helpers'
import { completeBusinessAcceptance } from './business-acceptance-helpers'

test('优化真实组件跨角色提交审批接单默认计划验收并保留父项目', async ({ page }) => {
  test.setTimeout(120_000)
  await page.setViewportSize({ width: 1920, height: 1080 })
  await page.goto('/')
  const initial = await snapshot(page)
  // Isolated Playwright storage prepares an already-delivered parent; all optimization transitions use UI.
  const parent = initial.database.projects[0]
  parent.status = 'completed'; parent.simpleStatus = 'completed'; parent.stage = '验收交付'
  parent.actualCompletedAt = '2026-09-10T00:00:00.000Z'
  await page.evaluate(value => localStorage.setItem('it-project-console.prototype.v1', JSON.stringify(value)), initial)
  await page.reload()
  expect(parent).toBeTruthy()
  await identity(page, '李思敏')
  await page.goto('/#/project-overview?projectId=' + parent.id)
  const detail = page.getByRole('dialog', { name: '项目详情', exact: true })
  await expect(detail).toBeVisible()
  await detail.getByRole('button', { name: '提优化需求', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '优化需求', exact: true })
  await expect(editor).toContainText('附件选填，可直接提交优化需求')
  await expect(editor).not.toContainText('提交评估至少需要一个上传完成的文件')
  await editor.getByLabel('优化标题', { exact: true }).fill('优化单节点浏览器闭环')
  await editor.getByLabel('当前问题', { exact: true }).fill('导出缺少部门字段')
  await editor.getByRole('button', { name: '提交评估', exact: true }).click()
  await expect(editor).toContainText('请填写期望效果 / 验收标准')
  await editor.getByLabel('期望效果 / 验收标准', { exact: true }).fill('导出包含正确部门，字段不为空')
  await date(editor, '期望上线日期', '2099-10-20')
  await page.screenshot({ animations: 'disabled', path: '../output/playwright/optimization-implemented/submit.png' })
  await editor.getByRole('button', { name: '提交评估', exact: true }).click()
  await expect(editor).not.toBeVisible()
  await detail.getByRole('button', { name: '关闭', exact: true }).click()
  await page.goto('/#/my-demands')
  await row(page, '优化单节点浏览器闭环').getByRole('button', { name: '编辑', exact: true }).click()
  await editor.getByLabel('期望效果 / 验收标准', { exact: true }).fill('')
  await editor.getByRole('button', { name: '保存修改', exact: true }).click()
  await expect(editor).toContainText('请填写期望效果 / 验收标准')
  expect((await snapshot(page)).database.demands.find(d => d.name === '优化单节点浏览器闭环')?.optimizationOutcome).toBe('导出包含正确部门，字段不为空')
  await editor.getByLabel('期望效果 / 验收标准', { exact: true }).fill('导出包含正确部门，字段不为空')
  await editor.getByRole('button', { name: '保存修改', exact: true }).click()
  await expect(editor).not.toBeVisible()
  await identity(page, '陈立峰')
  await page.goto('/#/my-demands')
  await row(page, '优化单节点浏览器闭环').getByRole('button', { name: '评估', exact: true }).click()
  const review = page.getByRole('dialog', { name: '需求评估 · 优化单节点浏览器闭环', exact: true })
  await expect(review).toContainText('导出包含正确部门')
  await select(page, review, '主负责人', '王浩然')
  await review.getByRole('button', { name: '提交工程师确认', exact: true }).click()
  await expect(review).not.toBeVisible()
  await acceptProposal(page, '优化单节点浏览器闭环')
  const projectCard = card(page, '优化单节点浏览器闭环')
  await expect(projectCard.locator('.stage-block')).toHaveCount(1)
  await expect(projectCard).toContainText('优化交付')
  await projectCard.getByRole('button', { name: '制定计划', exact: true }).click()
  const plan = page.getByRole('dialog', { name: '制定项目计划', exact: true })
  const starts = plan.locator('input[aria-label$="计划开始日期"]')
  const ends = plan.locator('input[aria-label$="计划结束日期"]')
  await expect(starts).toHaveCount(1)
  expect(await starts.inputValue()).toMatch(/^\d{4}-\d{2}-\d{2}$/)
  const start = new Date(await starts.inputValue() + 'T00:00:00Z'), end = new Date(await ends.inputValue() + 'T00:00:00Z')
  let workingDays = 0
  for (const d = new Date(start); d <= end; d.setUTCDate(d.getUTCDate() + 1)) if (![0, 6].includes(d.getUTCDay())) workingDays++
  expect(workingDays).toBe(3)
  await page.screenshot({ animations: 'disabled', path: '../output/playwright/optimization-implemented/plan.png' })
  await plan.getByRole('button', { name: '保存计划', exact: true }).click()
  await expect(plan).not.toBeVisible()
  const planned = (await snapshot(page)).database.projects.find(p => p.name === '优化单节点浏览器闭环')!
  await completeBusinessAcceptance(page, planned.id, '部门字段已补齐，导出验证通过')
  await expect(detail).toContainText('优化交付计划与执行')
  await page.screenshot({ animations: 'disabled', path: '../output/playwright/optimization-implemented/accepted.png' })
  const finished = await snapshot(page)
  expect(finished.database.projects.find(p => p.id === planned.id)).toMatchObject({ status: 'completed', parentProjectId: parent.id })
  expect(finished.database.projects.find(p => p.id === parent.id)).toEqual(parent)
  await detail.getByRole('button', { name: '关闭', exact: true }).click()
  await page.goto('/#/my-demands')
  await select(page, page.locator('body'), '需求类型', '优化需求')
  await expect(row(page, '优化单节点浏览器闭环')).toBeVisible()
  await page.reload()
  expect((await snapshot(page)).database.projects.find(p => p.id === planned.id)?.status).toBe('completed')
})
