import { expect, test, type Page, type Locator } from '@playwright/test'
import type { PrototypeSnapshot } from '../src/domain/prototype'

const key = 'it-project-console.prototype.v1'
const snapshot = (page: Page): Promise<PrototypeSnapshot> =>
  page.evaluate((key) => JSON.parse(localStorage.getItem(key)!), key)
const card = (page: Page, name: string) => page.locator('[data-project-id]').filter({ hasText: name })
const row = (page: Page, name: string) => page.getByRole('row').filter({ hasText: name })
async function identity(page: Page, name: string) {
  await page.getByRole('button', { name: '切换演示身份' }).click()
  await page.locator('.identity-menu-item').filter({ hasText: name }).click()
  await expect(page.getByRole('button', { name: '切换演示身份' })).toContainText(name)
}
async function date(drawer: Locator, name: string, value: string) {
  await drawer.getByLabel(name, { exact: true }).fill(value)
  await drawer.getByLabel(name, { exact: true }).press('Tab')
}
async function assignment(page: Page, drawer: Locator, collaborators = true) {
  await drawer.locator('.el-select').filter({ has: page.getByRole('combobox', { name: '主负责人', exact: true }) }).click()
  await page.getByRole('option', { name: '王浩然', exact: true }).click()
  if (collaborators) {
    await drawer.locator('.el-select').filter({ has: page.getByRole('combobox', { name: '协作人员', exact: true }) }).click()
    const listId = await drawer.getByRole('combobox', { name: '协作人员', exact: true }).getAttribute('aria-controls')
    const list = page.locator(`[id="${listId}"]`)
    await expect(list.getByRole('option', { name: '王浩然', exact: true })).toBeDisabled()
    await list.getByRole('option', { name: '赵清越', exact: true }).click()
    await drawer.getByRole('combobox', { name: '协作人员', exact: true }).press('Escape')
  }
  await date(drawer, '最初计划上线日期', '2099-10-20')
  await date(drawer, '最初计划交付日期', '2099-10-30')
  await date(drawer, '方案设计预计完成日期', '2099-10-10')
}

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
  await expect(page.getByRole('button', { name: '直接创建项目' })).toBeVisible()
})

test('同一需求经草稿、立项、主责整体更新、协作个人更新跨角色持久流转', async ({ page }) => {
  await identity(page, '李思敏')
  await page.getByRole('button', { name: '提交正式项目需求' }).click()
  let drawer = page.getByRole('dialog', { name: '提交正式项目需求' })
  const name = '端到端预算协同项目'
  await drawer.getByLabel('项目名称', { exact: true }).fill(name)
  await drawer.getByLabel('这次要解决什么问题（一句话）').fill('让预算审批结果对所有参与人可见')
  await date(drawer, '期望上线日期', '2099-10-20')
  const initial = await snapshot(page)
  await drawer.getByRole('button', { name: '提交评估' }).click()
  await expect(drawer.locator('.el-form-item__error').filter({ hasText: '至少上传一个文件' })).toBeVisible()
  expect((await snapshot(page)).database.demands).toEqual(initial.database.demands)
  await drawer.getByRole('button', { name: '保存草稿' }).click()
  await expect(row(page, name)).toContainText('草稿')
  const draft = (await snapshot(page)).database.demands.find((d) => d.name === name)!
  await row(page, name).getByRole('button', { name: '编辑', exact: true }).click()
  drawer = page.getByRole('dialog', { name: '编辑本人需求' })
  await drawer.locator('input[type=file]').setInputFiles({ name: '需求.txt', mimeType: 'text/plain', buffer: Buffer.from('需求说明') })
  await drawer.getByRole('button', { name: '重新提交' }).click()
  await expect(row(page, name)).toContainText('待评估')
  expect((await snapshot(page)).database.demands.filter((d) => d.name === name).map((d) => d.id)).toEqual([draft.id])
  await identity(page, '陈立峰')
  await page.goto('/#/my-demands')
  await row(page, name).getByRole('button', { name: '评估', exact: true }).click()
  drawer = page.getByRole('dialog', { name: `需求评估 · ${name}` })
  await assignment(page, drawer)
  await drawer.getByRole('button', { name: '通过并立项' }).click()
  await expect(row(page, name)).toContainText('已立项')
  const project = (await snapshot(page)).database.projects.find((p) => p.demandId === draft.id)!
  expect(project.stage).toBe('方案设计')
  expect((await snapshot(page)).database.projects.filter((p) => p.demandId === draft.id)).toHaveLength(1)
  await identity(page, '王浩然')
  await expect(card(page, name)).toContainText('主责')
  await card(page, name).getByRole('button', { name: '更新进度' }).click()
  drawer = page.getByRole('dialog', { name: '更新项目进度' })
  await drawer.getByRole('spinbutton', { name: '整体进度（%）' }).fill('100')
  await drawer.locator('.el-select').filter({ has: page.getByRole('combobox', { name: '当前阶段状态', exact: true }) }).click()
  await page.getByRole('option', { name: '已完成', exact: true }).click()
  await date(drawer, '下一阶段预计完成日期', '2099-10-15')
  await date(drawer, '当前预计交付日期', '2099-11-05')
  await drawer.locator('.el-select').filter({ has: page.getByRole('combobox', { name: '日期调整原因' }) }).click()
  await page.getByRole('option', { name: '等待外部资源', exact: true }).click()
  await drawer.getByLabel('日期调整说明').fill('等待预算接口联调窗口')
  await drawer.getByLabel('进展说明', { exact: true }).fill('方案已确认，进入开发编码')
  await drawer.getByRole('button', { name: '保存进度' }).click()
  await expect(drawer).not.toBeVisible()
  await expect(card(page, name)).toContainText('100%')
  const overall = (await snapshot(page)).database.projects.find((p) => p.id === project.id)!
  expect(overall).toMatchObject({ stage: '开发编码', status: 'active', archived: false, overallProgress: 100 })
  await identity(page, '赵清越')
  await expect(card(page, name)).toContainText('协作')
  await expect(card(page, name).getByRole('button', { name: '更新进度' })).toHaveCount(0)
  await card(page, name).getByRole('button', { name: '填写协作进展' }).click()
  drawer = page.getByRole('dialog', { name: '填写协作进展' })
  await expect(drawer.getByRole('spinbutton')).toHaveCount(0)
  await expect(drawer.getByRole('combobox')).toHaveCount(0)
  await drawer.getByLabel('进展说明', { exact: true }).fill('预算接口联调数据已准备')
  await drawer.getByRole('button', { name: '保存进度' }).click()
  await expect(drawer).not.toBeVisible()
  const afterPersonal = (await snapshot(page)).database.projects.find((p) => p.id === project.id)!
  expect({ ...afterPersonal, updatedAt: overall.updatedAt }).toEqual(overall)
  await identity(page, '陈立峰')
  await card(page, name).getByRole('button', { name: '详情', exact: true }).click()
  drawer = page.getByRole('dialog', { name: '项目详情', exact: true })
  for (const text of ['100%', '方案已确认，进入开发编码', '预算接口联调数据已准备', '2099-10-30 → 2099-11-05']) {
    await expect(drawer.getByText(text, { exact: false }).first()).toBeVisible()
  }
  await page.reload()
  await expect(page.getByRole('dialog', { name: '项目详情', exact: true })).toContainText('预算接口联调数据已准备')
  expect((await snapshot(page)).database.projects.find((p) => p.id === project.id)).toEqual(afterPersonal)
})

test('退回与拒绝必须说明原因，退回原单重提，拒绝后只读', async ({ page }) => {
  const name = '营销活动预算协同平台'
  await page.goto('/#/my-demands')
  const before = await snapshot(page)
  await row(page, name).getByRole('button', { name: '评估' }).click()
  let drawer = page.getByRole('dialog', { name: `需求评估 · ${name}` })
  await drawer.getByText('退回补充', { exact: true }).click()
  await drawer.getByRole('button', { name: '确认退回补充' }).click()
  await expect(drawer.getByText('请填写处理原因')).toBeVisible()
  expect((await snapshot(page)).database).toEqual(before.database)
  await drawer.getByLabel('处理原因').fill('请补充预算审批规则')
  await drawer.getByRole('button', { name: '确认退回补充' }).click()
  await expect(row(page, name)).toContainText('退回补充')
  await identity(page, '李思敏')
  await row(page, name).getByRole('button', { name: '补充重提' }).click()
  drawer = page.getByRole('dialog', { name: '编辑本人需求' })
  await expect(drawer).toContainText('请补充预算审批规则')
  await date(drawer, '期望上线日期', '2099-10-20')
  await drawer.getByRole('button', { name: '重新提交' }).click()
  await expect(row(page, name)).toContainText('待评估')
  expect((await snapshot(page)).database.demands.map((d) => d.id)).toEqual(before.database.demands.map((d) => d.id))
  await identity(page, '陈立峰')
  await page.goto('/#/my-demands')
  await row(page, name).getByRole('button', { name: '评估' }).click()
  drawer = page.getByRole('dialog', { name: `需求评估 · ${name}` })
  await drawer.getByText('不予立项', { exact: true }).click()
  await drawer.getByRole('button', { name: '确认不予立项' }).click()
  await expect(drawer.getByText('请填写处理原因')).toBeVisible()
  await drawer.getByLabel('处理原因').fill('现有系统已覆盖该范围')
  await drawer.getByRole('button', { name: '确认不予立项' }).click()
  await expect(row(page, name)).toContainText('不予立项')
  await identity(page, '李思敏')
  await expect(row(page, name).getByRole('button', { name: /编辑|补充重提/ })).toHaveCount(0)
  await row(page, name).getByRole('button', { name: '查看', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('现有系统已覆盖该范围')
})

test('直接创建不伪造需求，无关工程师只能查看，三档桌面无页面溢出', async ({ page }) => {
  const before = await snapshot(page)
  const name = '直接创建权限验收项目'
  await page.getByRole('button', { name: '直接创建项目' }).click()
  const drawer = page.getByRole('dialog', { name: '直接创建项目' })
  await drawer.getByLabel('项目名称', { exact: true }).fill(name)
  await drawer.getByLabel('需求部门', { exact: true }).fill('IT部')
  await assignment(page, drawer, false)
  await drawer.getByRole('button', { name: '创建项目', exact: true }).click()
  await expect(drawer).not.toBeVisible()
  const saved = await snapshot(page)
  expect(saved.database.demands).toEqual(before.database.demands)
  expect(saved.database.projects.find((p) => p.name === name)).toMatchObject({ source: 'direct', demandId: null, collaboratorIds: [] })
  await page.getByRole('dialog', { name: '项目详情', exact: true }).getByRole('button', { name: '关闭', exact: true }).click()
  await identity(page, '赵清越')
  await expect(card(page, name)).toHaveCount(0)
  await page.getByText('全部项目', { exact: true }).click()
  await expect(card(page, name)).toContainText('当前项目仅可查看')
  await expect(card(page, name).getByRole('button', { name: /更新进度|填写协作进展/ })).toHaveCount(0)
  for (const width of [1024, 1280, 1440]) {
    await page.setViewportSize({ width, height: 1000 })
    await expect(card(page, name)).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `../output/playwright/phase2-${width}.png`, fullPage: true })
  }
  await card(page, name).getByRole('button', { name: '详情', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '项目详情', exact: true })).toContainText('直接创建项目，无关联需求材料')
  await expect(page.getByRole('dialog').getByRole('button', { name: /更新进度|填写协作进展/ })).toHaveCount(0)
})

test('保存失败保留进度输入且不修改任何已保存数据，重试仍无假成功', async ({ page }) => {
  await identity(page, '王浩然')
  await page.evaluate((key) => {
    const data = JSON.parse(localStorage.getItem(key)!)
    data.scenario = 'save-error'
    localStorage.setItem(key, JSON.stringify(data))
  }, key)
  await page.reload()
  const before = await snapshot(page)
  await card(page, '客户数据治理一期').getByRole('button', { name: '更新进度' }).click()
  const drawer = page.getByRole('dialog', { name: '更新项目进度' })
  await drawer.getByLabel('进展说明', { exact: true }).fill('失败后保留的真实输入')
  await drawer.getByRole('spinbutton', { name: '整体进度（%）' }).fill('63')
  for (let attempt = 0; attempt < 2; attempt++) {
    await drawer.getByRole('button', { name: '保存进度' }).click()
    await expect(drawer.getByRole('alert')).toContainText(/失败/)
    await expect(drawer.getByLabel('进展说明', { exact: true })).toHaveValue('失败后保留的真实输入')
    await expect(drawer.getByRole('spinbutton', { name: '整体进度（%）' })).toHaveValue('63')
    expect(await snapshot(page)).toEqual(before)
  }
})
