import { planProject } from './review-helpers'
import { expect, test, type Page } from '@playwright/test'
import type { PrototypeSnapshot } from '../src/domain/prototype'
const key = 'it-project-console.prototype.v1'
const read = (page: Page): Promise<PrototypeSnapshot> => page.evaluate((k) => JSON.parse(localStorage.getItem(k)!), key)
const row = (page: Page, name: string) => page.getByRole('row').filter({ hasText: name })
const detail = (page: Page) => page.getByRole('dialog', { name: '项目详情', exact: true })
async function identity(page: Page, name: string) {
  await page.getByRole('button', { name: '切换演示身份' }).click()
  await page.locator('.identity-menu-item').filter({ hasText: name }).click()
  await expect(page.getByRole('button', { name: '切换演示身份' })).toContainText(name)
}
async function open(page: Page, id = 'P-2026-008') {
  await page.goto(`/#/monthly-gantt?projectId=${id}`)
  await expect(detail(page)).toBeVisible()
}
async function select(page: Page, label: string, option: string) {
  await page.locator('.el-select').filter({ has: page.getByRole('combobox', { name: label, exact: true }) }).click()
  await page.getByRole('option', { name: option, exact: true }).click()
}
test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
  await expect(page.getByRole('button', { name: '直接创建项目' })).toBeVisible({ timeout: 15000 })
})
test('验收完成自动完成项目不归档，刷新保持，管理员重开保留历史', async ({ page }) => {
  await page.evaluate((k) => {
    const data: PrototypeSnapshot = JSON.parse(localStorage.getItem(k)!)
    const p = data.database.projects[0]!
    p.stage = '验收交付'; p.simpleStatus = 'in-progress'; p.stagePlans = [{ stage: '验收交付', startDate: '2099-10-01', endDate: '2099-10-30', originalStartDate: '2099-10-01', originalEndDate: '2099-10-30' }]
    localStorage.setItem(k, JSON.stringify(data))
  }, key)
  await page.reload()
  await identity(page, '王浩然')
  await open(page)
  await expect(detail(page).getByRole('button', { name: '完成并归档', exact: true })).toHaveCount(0)
  await detail(page).getByRole('button', { name: '更新环节', exact: true }).click()
  const update = page.getByRole('dialog', { name: '更新环节', exact: true })
  await update.getByText('已完成', { exact: true }).click()
  await update.getByLabel('补充说明（选填）', { exact: true }).fill('验收签字已全部完成')
  await update.getByRole('button', { name: '保存更新' }).click()
  await expect(update).not.toBeVisible()
  await expect.poll(async () => (await read(page)).database.projects[0]!.status).toBe('completed')
  await expect(detail(page).getByRole('button', { name: '完成并归档', exact: true })).toHaveCount(0)
  await page.reload()
  expect((await read(page)).database.projects[0]).toMatchObject({ archived: false, status: 'completed' })
  await detail(page).getByRole('button', { name: '关闭', exact: true }).click()
  await identity(page, '陈立峰')
  await open(page)
  await detail(page).getByRole('button', { name: '重新打开', exact: true }).click()
  await expect(page.locator('.el-message-box__message')).toContainText('客户数据治理一期')
  await page.getByRole('button', { name: '确认重新打开', exact: true }).click()
  await expect(detail(page)).toContainText('验收签字已全部完成')
  await expect.poll(async () => (await read(page)).database.projects[0]!.status).toBe('active')
  expect((await read(page)).database.lifecycleEvents.map((e) => e.action)).toEqual(['reopen', 'complete'])
})
test('取消原因校验不写库，管理人员可删除任意项目并同步删除原需求', async ({ page }) => {
  await open(page)
  await expect(detail(page).getByRole('button', { name: '删除项目', exact: true })).toBeVisible()
  const before = await read(page)
  await detail(page).getByRole('button', { name: '取消项目', exact: true }).click()
  await expect(page.locator('.el-message-box__message')).toContainText('客户数据治理一期')
  await page.getByRole('button', { name: '确认取消项目' }).click()
  await expect(page.getByText('请填写 1～300 字原因', { exact: true })).toBeVisible()
  expect((await read(page)).database).toEqual(before.database)
  await page.locator('.el-message-box textarea').fill('业务范围变更，暂停项目')
  await page.getByRole('button', { name: '确认取消项目' }).click()
  await expect(detail(page)).toContainText('业务范围变更，暂停项目')
  await page.reload()
  expect((await read(page)).database.projects[0]!.status).toBe('cancelled')
  expect((await read(page)).database.progressUpdates).toEqual(before.database.progressUpdates)
  await detail(page).getByRole('button', { name: '关闭', exact: true }).click()
  await open(page, 'P-2026-004')
  await detail(page).getByRole('button', { name: '删除项目', exact: true }).click()
  await expect(page.locator('.el-message-box__message')).toContainText('经营分析指标统一')
  await page.locator('.el-message-box textarea').fill('重复立项误建')
  await expect(page.locator('.el-message-box__message')).toContainText('原需求')
  await page.getByRole('button', { name: '确认删除项目', exact: true }).click()
  await expect(detail(page)).toContainText('项目不存在或已移除')
  const saved = await read(page)
  expect(saved.database.projects.some((p) => p.id === 'P-2026-004')).toBe(false)
  expect(saved.database.demands.some((d) => d.id === 'D-2026-004')).toBe(false)
})
test('本人需求撤回重提保持原单，删除带确认且他人不能维护', async ({ page }) => {
  const name = '营销活动预算协同平台'
  await page.goto('/#/my-demands')
  await expect(row(page, name).getByRole('button', { name: '更多需求操作' })).toHaveCount(0)
  await identity(page, '李思敏')
  await page.goto('/#/my-demands')
  await row(page, name).getByRole('button', { name: '更多需求操作' }).click()
  await page.getByRole('menuitem', { name: '撤回需求' }).click()
  await expect(page.locator('.el-message-box__message')).toContainText(name)
  await page.getByRole('button', { name: '确认撤回', exact: true }).click()
  await expect(row(page, name)).toContainText('已撤回')
  await row(page, name).getByRole('button', { name: /编辑|重新提交/ }).click()
  const editor = page.getByRole('dialog', { name: '编辑本人需求' })
  await editor.getByLabel('期望上线日期', { exact: true }).fill('2099-11-20')
  await editor.getByLabel('期望上线日期', { exact: true }).press('Tab')
  await editor.getByRole('button', { name: '重新提交', exact: true }).click()
  await expect(row(page, name)).toContainText('待评估')
  expect((await read(page)).database.demands.filter((d) => d.name === name).map((d) => d.id)).toEqual(['D-2026-013'])
  await row(page, name).getByRole('button', { name: '更多需求操作' }).click()
  await page.getByRole('menuitem', { name: '删除需求' }).click()
  await expect(page.locator('.el-message-box__message')).toContainText(name)
  await page.getByRole('button', { name: '确认删除', exact: true }).click()
  await expect(row(page, name)).toHaveCount(0)
})
test('管理员授权刷新有效，撤权恢复角色，自撤权路由及最后管理员保护', async ({ page }) => {
  await page.goto('/#/manager-grants')
  await row(page, 'user-manager-chen').getByRole('button', { name: '移除权限' }).click()
  await page.getByRole('button', { name: '确认移除' }).click()
  await expect(page.getByRole('alert')).toContainText(/最后一名管理人员/)
  await page.getByRole('button', { name: '添加管理人员', exact: true }).click()
  await select(page, '组织成员', '李思敏 · 市场运营部')
  await page.getByRole('button', { name: '确认添加' }).click()
  await expect(row(page, '李思敏')).toContainText('有效')
  await page.reload()
  await expect(row(page, '李思敏')).toContainText('陈立峰')
  await row(page, '李思敏').getByRole('button', { name: '移除权限' }).click()
  await page.getByRole('button', { name: '确认移除' }).click()
  await expect(row(page, '李思敏')).toHaveCount(0)
  expect((await read(page)).database.users.find((u) => u.name === '李思敏')!.role).toBe('business')
  await page.getByRole('button', { name: '添加管理人员', exact: true }).click()
  await select(page, '组织成员', '王浩然 · 信息技术部')
  await page.getByRole('button', { name: '确认添加' }).click()
  await expect(row(page, '王浩然')).toBeVisible()
  await row(page, 'user-manager-chen').getByRole('button', { name: '移除权限' }).click()
  await page.getByRole('button', { name: '确认移除' }).click()
  await expect(page).not.toHaveURL(/manager-grants/)
  await page.goto('/#/manager-grants')
  await expect(page).toHaveURL(/403/)
})
test('甘特跨月同源进度，月份切换，冻结左栏与三档桌面截图', async ({ page }) => {
  await page.goto('/#/monthly-gantt')
  const heading = page.getByRole('heading', { name: /\d{4}-\d{2} 甘特图/ })
  const month = await heading.textContent()
  const track = page.getByRole('button', { name: '查看客户数据治理一期详情' })
  await expect(track).toContainText('正常推进')
  await track.hover()
  await expect(page.locator('.gantt-tip').filter({ hasText: '客户数据治理一期' })).toContainText('预计交付')
  await page.getByRole('button', { name: '下一月', exact: true }).click()
  await expect(heading).not.toHaveText(month!)
  await expect(track).toBeVisible()
  await page.getByRole('button', { name: '上一月', exact: true }).click()
  await expect(heading).toHaveText(month!)
  await page.getByRole('button', { name: '返回本月' }).click()
  for (const width of [1024, 1280, 1440]) {
    await page.setViewportSize({ width, height: 1000 })
    const cell = page.locator('.project-cell').first()
    const x = (await cell.boundingBox())!.x
    await page.locator('.gantt-scroll').evaluate((el) => { el.scrollLeft = 400 })
    expect(Math.abs((await cell.boundingBox())!.x - x)).toBeLessThan(2)
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `../output/playwright/phase3-gantt-${width}.png`, fullPage: true })
    await page.locator('.gantt-scroll').evaluate((el) => { el.scrollLeft = 0 })
  }
  await track.click()
  await expect(detail(page)).toContainText('七环节计划与执行')
})
test('职责待办评估退回到本人补充，重提后消失', async ({ page }) => {
  await page.goto('/#/today-tasks')
  const task = page.locator('[data-task-id="D-2026-013"]')
  await task.getByRole('button', { name: '评估需求' }).click()
  const review = page.getByRole('dialog', { name: '需求评估 · 营销活动预算协同平台' })
  await review.getByText('退回补充', { exact: true }).click()
  await review.getByLabel('处理原因').fill('补充预算规则')
  await review.getByRole('button', { name: '确认退回补充' }).click()
  await expect(task).toHaveCount(0)
  await identity(page, '李思敏')
  await page.goto('/#/today-tasks')
  await expect(task).toContainText('补充预算规则')
  await task.getByRole('button', { name: '补充重提' }).click()
  const editor = page.getByRole('dialog', { name: '编辑本人需求' })
  await editor.getByLabel('期望上线日期', { exact: true }).fill('2099-11-20')
  await editor.getByLabel('期望上线日期', { exact: true }).press('Tab')
  await editor.getByRole('button', { name: '重新提交', exact: true }).click()
  await expect(task).toHaveCount(0)
  await expect(page.getByText('当前无待处理事项')).toBeVisible()
})

test('主责停更更新后任务消失，协作记录不代替整体更新', async ({ page }) => {
  await planProject(page, '客户数据治理一期')
  await page.evaluate((k) => {
    const data: PrototypeSnapshot = JSON.parse(localStorage.getItem(k)!)
    const p = data.database.projects[0]!
    p.expectedLaunchDate = p.originalLaunchDate = '2099-10-01'
    p.expectedDeliveryDate = p.originalDeliveryDate = '2099-10-30'
    p.stageExpectedDate = '2099-09-20'
    p.lastOverallUpdatedAt = '2026-08-01T00:00:00Z'
    data.database.scheduleChanges = data.database.scheduleChanges.filter((s) => s.projectId !== p.id)
    localStorage.setItem(k, JSON.stringify(data))
  }, key)
  await page.reload()
  await identity(page, '赵清越')
  await page.goto('/#/today-tasks')
  const task = page.locator('[data-task-id="P-2026-008"]')
  const before = (await read(page)).database.projects[0]!.lastOverallUpdatedAt
  await task.getByRole('button', { name: '填写协作进展' }).click()
  let editor = page.getByRole('dialog', { name: '填写协作进展' })
  await editor.getByLabel('进展说明', { exact: true }).fill('协作准备完成')
  await editor.getByRole('button', { name: '保存更新' }).click()
  await expect(editor).not.toBeVisible()
  expect((await read(page)).database.projects[0]!.lastOverallUpdatedAt).toBe(before)
  await expect(task).toContainText('未更新')
  await identity(page, '王浩然')
  await page.goto('/#/today-tasks')
  await task.getByRole('button', { name: '更新环节' }).click()
  editor = page.getByRole('dialog', { name: '更新环节' })
  await editor.getByLabel('补充说明（选填）', { exact: true }).fill('主责确认进度，风险已处理')
  await editor.getByRole('button', { name: '保存更新' }).click()
  await expect(editor).not.toBeVisible()
  await expect(task).toHaveCount(0)
  await page.reload()
  await expect(task).toHaveCount(0)
})
test('管理纠正必填原因，纠正后详情显示操作者及审计前后值', async ({ page }) => {
  await open(page)
  await detail(page).getByRole('button', { name: '管理纠正', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '管理纠正', exact: true })
  const before = (await read(page)).database
  await expect(editor.getByRole('option', { name: '需求受理', exact: true })).toHaveCount(0)
  await editor.getByRole('button', { name: '保存纠正' }).click()
  await expect(editor.getByText('请填写此项', { exact: true })).toBeVisible()
  expect((await read(page)).database).toEqual(before)
  await editor.getByLabel('纠正原因', { exact: true }).fill('对照交付清单纠正为实际进度')
  await editor.getByRole('button', { name: '保存纠正' }).click()
  await expect(editor).not.toBeVisible()
  await expect(detail(page)).toContainText('开发编码')
  await expect(detail(page)).toContainText('对照交付清单纠正为实际进度')
  await expect(detail(page)).toContainText('陈立峰')
  const event = (await read(page)).database.lifecycleEvents[0]!
  expect(event).toMatchObject({ action: 'correct', authorId: 'user-manager-chen', after: { stage: '开发编码' }, before: { stage: before.projects[0]!.stage } })
  await page.reload()
  await expect(detail(page)).toContainText('开发编码')
})
