import { expect, test } from '@playwright/test'
import { card, date, identity, reset, snapshot } from './review-helpers'
test('完整编辑复用卡片与详情，放弃提醒、保存原因、持久化和中文历史', async ({ page }) => {
  await page.goto('/')
  await reset(page)
  await identity(page, '陈立峰')
  const initial = await snapshot(page)
  const project = initial.database.projects.find(p => p.status === 'active' && !p.archived)!
  await card(page, project.name).getByRole('button', { name: '编辑项目', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '编辑项目', exact: true })
  await date(editor, '需求首次提出日期', '2026-07-15')
  await editor.getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByText('未保存', { exact: false }).first()).toBeVisible()
  await page.getByRole('button', { name: '继续编辑', exact: true }).click()
  await editor.getByRole('button', { name: '保存修改', exact: true }).click()
  const confirmation = page.getByRole('dialog', { name: '确认本次修改', exact: true })
  await confirmation.getByRole('button', { name: '确认保存', exact: true }).click()
  await expect(confirmation).toContainText('请填写本次修改原因')
  await confirmation.getByLabel('修改原因').fill('核对原始需求日期')
  await confirmation.getByRole('button', { name: '确认保存', exact: true }).click()
  await expect(editor).not.toBeVisible()
  expect((await snapshot(page)).database.projects.find(p => p.id === project.id)?.firstRequestedOn).toBe('2026-07-15')
  await page.reload()
  await card(page, project.name).getByRole('button', { name: '详情', exact: true }).click()
  const detail = page.getByRole('dialog').filter({ hasText: '状态与管理历史' })
  await expect(detail).toContainText('需求首次提出日期：2026-07-15')
  await detail.getByRole('button', { name: '编辑项目', exact: true }).click()
  await expect(editor.getByLabel('需求首次提出日期', { exact: true })).toHaveValue('2026-07-15')
})
