import { expect, test } from '@playwright/test'
import { date, identity, row, select, snapshot } from './review-helpers'

test('工程师退回→管理退业务补材料→业务原单重提，旧接单链接失效', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/')
  await expect(page.getByRole('button', { name: '直接创建项目', exact: true })).toBeVisible()
  const demand = (await snapshot(page)).database.demands.find(d => d.status === 'pending' && d.submitterId === 'user-business-li')!
  expect(demand).toBeTruthy()
  await page.goto('/#/my-demands')
  await row(page, demand.name).getByRole('button', { name: '立项审批', exact: true }).click()
  let drawer = page.getByRole('dialog', { name: '立项审批 · ' + demand.name })
  await select(page, drawer, '主负责人', '王浩然')
  await date(drawer, '审批确认上线日期', '2099-10-20')
  await drawer.getByRole('button', { name: '提交工程师确认' }).click()
  await expect(drawer).not.toBeVisible()
  const proposal = (await snapshot(page)).database.projectProposals!.find(p => p.demandId === demand.id)!
  await identity(page, '王浩然')
  await page.goto('/#/today-tasks?proposalId=' + proposal.id)
  drawer = page.getByRole('dialog', { name: '接单详情 · ' + demand.name })
  await drawer.getByLabel('退回评估原因（退回时必填）').fill('需要补充业务流程图')
  await drawer.getByRole('button', { name: '退回管理评估', exact: true }).click()
  await expect(drawer).not.toBeVisible()
  await identity(page, '陈立峰')
  await page.goto('/#/today-tasks?proposalId=' + proposal.id)
  drawer = page.getByRole('dialog', { name: '接单详情 · ' + demand.name })
  await expect(drawer).toContainText('需要补充业务流程图')
  await expect(drawer).toContainText('主负责人：王浩然')
  await drawer.getByRole('button', { name: '退回业务补充 / 不予立项' }).click()
  const review = page.getByRole('dialog', { name: '立项审批 · ' + demand.name })
  await expect(review.getByRole('radio', { name: '批准立项', exact: true })).toHaveCount(0)
  await review.getByLabel('处理原因').fill('请补充业务流程图再提交')
  await review.getByRole('button', { name: '确认退回补充' }).click()
  await expect(review).not.toBeVisible()
  expect((await snapshot(page)).database.projectProposals?.find(p => p.id === proposal.id)).toBeUndefined()
  await identity(page, '李思敏')
  await page.goto('/#/my-demands')
  await row(page, demand.name).getByRole('button', { name: '补充重提', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '编辑本人需求' })
  await editor.getByRole('button', { name: '重新提交', exact: true }).click()
  await expect(editor).not.toBeVisible()
  await expect(row(page, demand.name)).toContainText('待立项审批')
  await page.goto('/#/today-tasks?proposalId=' + proposal.id)
  await expect(page.getByText('待接单记录不存在或无权访问，请刷新待办', { exact: true })).toBeVisible()
})
