const { chromium } = require(require.resolve('@playwright/test', {paths:[process.cwd()]}));
const path = require('path');
const assert = require('assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1080}});
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  const open=role=>page.goto('file:///'+path.join(__dirname,role+'.html').replaceAll('\\','/'));
  await open('manager');
  assert.equal(await page.locator('.obar').count(),5);
  assert.equal(await page.locator('.pcard').count(),14);
  assert.equal(await page.locator('.lrow').count(),8);
  const sidebar=await page.locator('.sidebar').boundingBox();assert(sidebar.height>1000);
  await page.locator('.ovcol').first().hover();
  assert((await page.locator('#gtip').innerText()).includes('在手项目'));
  await page.mouse.move(1400,80);
  await page.screenshot({path:path.join(__dirname,'manager-overview.png'),fullPage:true});
  await page.locator('#navBar button').filter({hasText:'甘特图'}).click();
  assert.equal(await page.locator('.grow:not(.ghrow)').count(),14);
  assert(await page.locator('.gtrack svg line[stroke-dasharray]').count()>0);
  await page.locator('.gtrack svg rect[onclick]').first().hover();
  assert((await page.locator('#gtip').innerText()).length>20);
  await page.mouse.move(1400,80);
  await page.screenshot({path:path.join(__dirname,'manager-gantt.png'),fullPage:true});
  await page.locator('#navBar button').filter({hasText:'需求池'}).click();
  assert(await page.locator('.dseg').count()>1);
  assert(await page.locator('.ddseg').count()>1);
  assert((await page.locator('#pane-demand').innerText()).includes('按月需求趋势'));
  const ring=await page.locator('#pane-demand .dring svg').first().boundingBox();
  await page.mouse.move(ring.x+94,ring.y+22);
  assert((await page.locator('#gtip').innerText()).includes('杜鹃'));
  await page.mouse.move(1400,80);
  await page.screenshot({path:path.join(__dirname,'manager-demands.png'),fullPage:true});
  await page.evaluate(()=>{state.fDept='供应链部';renderDemands()});
  assert.equal(await page.locator('.tbl-fluid tbody tr').count(),3);
  for(const role of ['engineer','business']){
    await open(role);
    await page.screenshot({path:path.join(__dirname,role+'-home.png'),fullPage:true});
    const count=await page.evaluate(()=>ART_ROLE==='engineer'?filterProjects().length:artDemands().length);
    assert(count>0&&count<14);
    assert.equal(await page.locator('button[onclick^="openProjectModal"]:visible').count(),0);
    assert.equal(await page.locator('button[onclick^="openDemandAssign"]:visible').count(),0);
    await page.locator('.art-scope button').filter({hasText:'全部数据'}).click();
    assert.equal(await page.evaluate(()=>ART_SCOPE),'all');
    await page.locator('#navBar button').filter({hasText:'甘特图'}).click();
    assert.equal(await page.locator('.grow:not(.ghrow)').count(),14);
    await page.screenshot({path:path.join(__dirname,role+'-gantt.png'),fullPage:true});
  }
  await open('engineer');
  assert(await page.evaluate(()=>computePeople(state.rankMonth).every(row=>state.projects.filter(p=>!artMine(p)).every(p=>!rankTipHtml(row.name,state.rankMonth).includes(p.name)))));
  const collab=await page.evaluate(()=>state.projects.find(p=>p.owner!==ART_USER&&artMine(p))?.rid);
  assert(collab);
  await page.evaluate(id=>openProgressModal(id),collab);
  assert.equal(await page.locator('#art-collab-work').count(),1);
  assert.equal(await page.locator('#g_phase').count(),0);
  await page.locator('#art-collab-work').fill('协作视角验证进展');
  const before=await page.evaluate(id=>JSON.stringify(findProject(id)),collab);
  await page.locator('.modal button').filter({hasText:'保存进展'}).click();
  assert.equal(await page.evaluate(id=>JSON.stringify(findProject(id)),collab),before);
  assert(await page.evaluate(()=>state.logs.some(l=>l.work==='协作视角验证进展')));
  await open('business');
  await page.evaluate(()=>openProjectDetail(state.projects[0].rid));
  assert.equal(await page.locator('.modal button[onclick^="openProgressModal"]:visible').count(),0);
  for(const width of [1024,1280,1440]){await page.setViewportSize({width,height:1080});await open('manager');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
  assert.deepEqual(errors,[]);
  console.log('PASS: 14项目/11需求，5指标柱、8人负载、双分布环图/条图、月度趋势、14行甘特/今日线/悬停、角色范围切换、协作隔离、1024/1280/1440页面无横溢出；无JS错误。');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
